[package]
name = "tinyweb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.2.2"
serde_json = "1.0.0"
serde = { verson="1.0", features = ["derive"]}
